[package]
name = "othello-client"
version = "0.1.0"
authors = ["Guillaume Gauvrit <guillaume@gauvr.it>"]

[dependencies]

stdweb = "^0.4.6"
yew = "^0.4"
log = "^0.4"
web_logger = "^0.1"

failure = "^0.1.1"
serde = "^1.0.66"
serde_derive = "^1.0.66"
serde_json = "^1.0"
